# Generated by Django 4.2.1 on 2023-05-22 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("failure_count", models.SmallIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExternalUserToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("code", models.PositiveIntegerField(null=True)),
                ("secret", models.CharField(max_length=100)),
                ("expiry", models.DateTimeField()),
                ("redeemed", models.DateTimeField(blank=True, null=True)),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "external_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PM", "Project Manager"),
                            ("DR", "Direct Report"),
                            ("WT", "Wider Team"),
                            ("EX", "External"),
                            ("SA", "Self-Assessment"),
                            ("A1", "Assessment - Part 1"),
                        ],
                        max_length=2,
                    ),
                ),
                ("closes_override", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["reviewer__username", "reviewee__username"],
            },
        ),
        migrations.CreateModel(
            name="ReviewForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PM", "Project Manager"),
                            ("DR", "Direct Report"),
                            ("WT", "Wider Team"),
                            ("EX", "External"),
                            ("SA", "Self-Assessment"),
                            ("A1", "Assessment - Part 1"),
                        ],
                        max_length=2,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ReviewFormQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="teamsite_staff_reviews.reviewform",
                    ),
                ),
            ],
            options={
                "ordering": ["form", "sequence"],
            },
        ),
        migrations.CreateModel(
            name="ReviewPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField()),
                (
                    "round",
                    models.CharField(
                        choices=[("FY", "Full Year"), ("MY", "Mid Year")], max_length=2
                    ),
                ),
            ],
            options={
                "unique_together": {("year", "round")},
            },
        ),
        migrations.CreateModel(
            name="ExternalInvitation",
            fields=[
                (
                    "nomination",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="invitation",
                        serialize=False,
                        to="teamsite_staff_reviews.nomination",
                    ),
                ),
                ("code", models.PositiveIntegerField(blank=True, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="teamsite_staff_reviews.externaluser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("OPEN", "1. Opens"),
                            ("NOMINATIONS", "2. Nominations Open"),
                            ("NOMINATIONS_CLOSE", "3. Nominations Close"),
                            ("FEEDBACK_OPENS", "4. Feedback Opens"),
                            ("FEEDBACK_CLOSE", "5. Feedback Closes"),
                            ("PART1", "6. Part 1"),
                            ("REVIEW_MEETINGS", "7. Review Meetings"),
                            ("ONE_ON_ONE", "8. 1-on-1"),
                            ("PART2", "9. Part 2"),
                            ("OTHER", "10. Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("visible", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("configuration", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField()),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="teamsite_staff_reviews.reviewperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="reviewform",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="forms",
                to="teamsite_staff_reviews.reviewperiod",
            ),
        ),
        migrations.AddField(
            model_name="nomination",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nominations",
                to="teamsite_staff_reviews.reviewperiod",
            ),
        ),
        migrations.AddField(
            model_name="nomination",
            name="reviewee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewee_nominations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="nomination",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviewer_nominations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ExternalNomination",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("teamsite_staff_reviews.nomination",),
        ),
        migrations.CreateModel(
            name="ReviewFormResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "nomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="teamsite_staff_reviews.nomination",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="teamsite_staff_reviews.reviewformquestion",
                    ),
                ),
            ],
            options={
                "unique_together": {("nomination", "question")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="reviewform",
            unique_together={("role", "period")},
        ),
        migrations.AlterUniqueTogether(
            name="nomination",
            unique_together={("reviewee", "reviewer", "external_email")},
        ),
        migrations.CreateModel(
            name="ExternalInvitationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_time", models.DateTimeField(auto_now_add=True)),
                ("sent_to", models.EmailField(max_length=254)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="teamsite_staff_reviews.externalinvitation",
                    ),
                ),
            ],
        ),
    ]
